### ISSUE TITLE
Crashing the game and causing world won't load anymore

### ISSUE THREAD

**Issue by EGOIST1372** [A5b84/interdimensional-map-markers#1]
Hi
with this mod and item held info when using a blank map and creating a filled map causing the game crash and after that world would not load and giving error "server closed connection lost"

here is the log:
tried to open a blank map to make a filled map and crash happened and world corrupted (after I removed this mod world load again).

here is the crash log:

---- Minecraft Crash Report ----
// Don't do that.

Time: 6/20/22, 1:13 PM
Description: Ticking player

java.lang.NoSuchMethodError: 'double net.minecraft.class_2874.method_31110()'
	at net.minecraft.item.map.MapState.getCoordinateScale(MapState:691)
	at net.minecraft.item.map.MapState.localvar$ddp000$adjustX(MapState:628)
	at net.minecraft.item.map.MapState.addIcon(MapState)
	at net.minecraft.item.map.MapState.update(MapState:293)
	at net.minecraft.item.FilledMapItem.inventoryTick(FilledMapItem:335)
	at net.minecraft.item.ItemStack.inventoryTick(ItemStack:542)
	at net.minecraft.entity.player.PlayerInventory.updateItems(PlayerInventory:255)
	at net.minecraft.entity.player.PlayerEntity.tickMovement(PlayerEntity:566)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2384)
	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity:283)
	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:485)
	at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler:241)
	at net.minecraft.network.ClientConnection.tick(ClientConnection:246)
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:182)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:886)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_22.getCoordinateScale(class_22.java:691)
	at net.minecraft.class_22.localvar$ddp000$adjustX(class_22.java:628)
	at net.minecraft.class_22.method_107(class_22.java)
	at net.minecraft.class_22.method_102(class_22.java:293)
	at net.minecraft.class_1806.method_7888(class_1806.java:335)
	at net.minecraft.class_1799.method_7917(class_1799.java:542)
	at net.minecraft.class_1661.method_7381(class_1661.java:255)
	at net.minecraft.class_1657.method_6007(class_1657.java:566)
	at net.minecraft.class_1309.method_5773(class_1309.java:2384)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 389
	Entity Name: EGOIST23
	Entity's Exact location: 83.58, 23.00, -89.20
	Entity's Block location: World: (83,23,-90), Section: (at 3,7,6 in 5,1,-6; chunk contains blocks 80,-64,-96 to 95,319,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,Attributes:[{Base:0.0d,Name:"minecraft:generic.knockback_resistance"},{Base:4.0d,Name:"minecraft:generic.attack_speed"},{Base:0.10000000149011612d,Name:"minecraft:generic.movement_speed"},{Base:0.0d,Name:"minecraft:generic.armor_toughness"},{Base:0.0d,Name:"minecraft:generic.armor"},{Base:1.0d,Name:"minecraft:generic.attack_damage"}],Brain:{memories:{}},DataVersion:3105,DeathTime:0s,Dimension:"minecraft:overworld",EnderItems:[],FallDistance:0.0f,FallFlying:0b,Fire:-20s,Health:18.798153f,HurtByTimestamp:15584,HurtTime:0s,Inventory:[{Count:1b,Slot:0b,id:"minecraft:filled_map",tag:{map:3}},{Count:1b,Slot:4b,id:"minecraft:netherite_pickaxe",tag:{Damage:7,Enchantments:[{id:"minecraft:silk_touch",lvl:1s}],RepairCost:1}},{Count:1b,Slot:5b,id:"minecraft:map"},{Count:1b,Slot:6b,id:"minecraft:shears",tag:{Damage:16}},{Count:1b,Slot:7b,id:"minecraft:netherite_sword",tag:{Damage:29,Enchantments:[{id:"minecraft:sharpness",lvl:5s}],RepairCost:1}},{Count:1b,Slot:8b,id:"minecraft:flint_and_steel",tag:{Damage:14}},{Count:1b,Slot:9b,id:"minecraft:sea_lantern"},{Count:1b,Slot:10b,id:"minecraft:anvil"},{Count:1b,Slot:11b,id:"minecraft:music_disc_pigstep"},{Count:1b,Slot:12b,id:"minecraft:sheep_spawn_egg"},{Count:63b,Slot:13b,id:"minecraft:glass_pane"},{Count:1b,Slot:14b,id:"minecraft:chicken_spawn_egg"},{Count:5b,Slot:15b,id:"minecraft:torch"},{Count:29b,Slot:16b,id:"minecraft:cooked_porkchop"},{Count:4b,Slot:17b,id:"minecraft:stick"},{Count:62b,Slot:18b,id:"minecraft:slime_block"},{Count:64b,Slot:19b,id:"minecraft:wolf_spawn_egg"},{Count:8b,Slot:20b,id:"minecraft:paper"},{Count:2b,Slot:22b,id:"minecraft:glow_ink_sac"},{Count:1b,Slot:23b,id:"minecraft:filled_map",tag:{map:1}},{Count:1b,Slot:24b,id:"minecraft:music_disc_otherside"},{Count:64b,Slot:25b,id:"minecraft:coal_block"},{Count:39b,Slot:26b,id:"minecraft:cooked_chicken"},{Count:1b,Slot:27b,id:"minecraft:turtle_helmet",tag:{Damage:32}},{Count:1b,Slot:28b,id:"minecraft:painting"},{Count:1b,Slot:29b,id:"minecraft:glow_item_frame"},{Count:1b,Slot:30b,id:"minecraft:bat_spawn_egg"},{Count:62b,Slot:31b,id:"minecraft:name_tag"},{Count:1b,Slot:32b,id:"minecraft:water_bucket"},{Count:1b,Slot:33b,id:"minecraft:flower_pot"},{Count:2b,Slot:34b,id:"minecraft:item_frame"},{Count:1b,Slot:35b,id:"minecraft:lantern"},{Count:1b,Slot:100b,id:"minecraft:netherite_boots",tag:{Damage:40}},{Count:1b,Slot:101b,id:"minecraft:diamond_leggings",tag:{Damage:40,Enchantments:[{id:"minecraft:protection",lvl:4s}],RepairCost:1}},{Count:1b,Slot:102b,id:"minecraft:leather_chestplate",tag:{Damage:6}},{Count:1b,Slot:103b,id:"minecraft:chainmail_helmet",tag:{Damage:6,RepairCost:0,display:{Name:'{"text":"Allium Crown"}'}}}],Invulnerable:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,PortalCooldown:0,Pos:[83.583362522692d,23.0d,-89.20490305463049d],Rotation:[68.03f,13.349794f],Score:769,SelectedItemSlot:5,SleepTimer:0s,SpawnAngle:-171.57959f,SpawnDimension:"minecraft:overworld",SpawnForced:0b,SpawnX:83,SpawnY:23,SpawnZ:-94,UUID:[I;-2137839841,-1255387845,-1392100484,1468956888],XpLevel:23,XpP:0.23376608f,XpSeed:161837829,XpTotal:769,abilities:{flySpeed:0.05f,flying:0b,instabuild:1b,invulnerable:1b,mayBuild:1b,mayfly:1b,walkSpeed:0.1f},cardinal_components:{"onsoulfire:on_soul_fire":{OnSoulFire:0b}},foodExhaustionLevel:1.4756193f,foodLevel:12,foodSaturationLevel:0.0f,foodTickTimer:0,playerGameType:1,previousPlayerGameType:0,recipeBook:{isBlastingFurnaceFilteringCraftable:0b,isBlastingFurnaceGuiOpen:0b,isFilteringCraftable:0b,isFurnaceFilteringCraftable:0b,isFurnaceGuiOpen:0b,isGuiOpen:0b,isSmokerFilteringCraftable:0b,isSmokerGuiOpen:0b,recipes:{cooldown_ticks:0,ticks_since_last_warning:600,warning_level:0}}
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:485)
	at net.minecraft.class_3244.method_18784(class_3244.java:241)
	at net.minecraft.class_2535.method_10754(class_2535.java:246)
	at net.minecraft.class_3242.method_14357(class_3242.java:182)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2489239616 bytes (2373 MiB) / 6039797760 bytes (5760 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 980M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1617
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 59898.93
	Virtual memory used (MB): 55189.63
	Swap memory total (MB): 27195.07
	Swap memory used (MB): 4260.57
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Loaded Shaderpack: (off)
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		advancementinfo: AdvancementInfo 1.19-fabric0.53.3-1.3.1
		ambientenvironment: Ambient Environment 8.0+1
		antighost: AntiGhost 1.19-fabric0.55.3-1.1.5
		architectury: Architectury 5.7.27
		armorchroma: Armor Chroma 1.2.2
		audioplayer: AudioPlayer 1.19-1.0.3
		auudio: Auudio 1.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.3
		betterf3: BetterF3 1.3.1
		bettermounthud: Better Mount HUD 1.1.4
		betterpingdisplay: Better Ping Display 1.1.1
		bettersafebed: BetterSafeBed a
		biomeinfo: BiomeInfo 1.19-11
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.5.0
		boatiview: Boat Item View Fabric 0.0.3
		bookshelf: Bookshelf 14.0.3
		caffeineconfig: CaffeineConfig 1.0.0+1.17
		camerautils: Camera Utils 1.19-1.0.0
		capetweaks: Cape Tweaks 1.0.1
		cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
		cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
		cem: Custom Entity Models 0.7.1
		chat-up: Chat Up! 2.0
		chat_heads: Chat Heads 0.6.0
		chisel: Chisel Refabricated 1.4.6
		citresewn: CIT Resewn 1.1.0+1.19
		citresewn-defaults: CIT Resewn: Defaults 1.1.0+1.19
		cleanview: CleanView 1.19-v1-fabric
		clear-skies: Clear Skies 2.0.93
		clickadv: Clickable Advancements Mod 2.5
		clickthrough: ClickThrough 1.19-fabric0.53.3-0.4
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config: Cloth Config v6 7.0.72
		clumps: Clumps 9.0.0+1
		coat: Coat 1.0.0-beta.17+mc22w17a
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		completeconfig: CompleteConfig 2.0.0
		completeconfig-base: completeconfig-base 2.0.0
		completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
		completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		config2brigadier: Config to Brigadier 1.1.3
		continuity: Continuity 2.0.0+1.19
		controlling: Controlling For Fabric 10.0+1
		crowdin-translate: CrowdinTranslate 1.4+1.19
		cullleaves: Cull Leaves 2.3.4
		darkpaintings: DarkPaintings 11.0.2
		dashloader: DashLoader 4.0.0+1.19
		deathlog: DeathLog 0.2.9+1.19
		dev_quantumfusion_hyphen: Hyphen 0.2.2
		dev_quantumfusion_taski: Taski 1.1.0
		drippyloadingscreen: Drippy Loading Screen 1.6.4
		dynamicfps: Dynamic FPS 2.2.0
		eatinganimationid: Eating Animation 1.8.1-beta
		enhancedblockentities: Enhanced Block Entities 0.7+1.19
		entity_texture_features: Entity Texture Features 3.1.3
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabrictailor: Fabric Tailor 1.8.3
		fallingleaves: Falling Leaves 1.12.1+1.19
		fancymenu: FancyMenu 2.8.0
		fastopenlinksandfolders: FastOpenResourcePacks 1.1.1
		ferritecore: FerriteCore 4.2.1
		fmextension_audio: FancyMenu Audio Extension 1.1.0
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		freecam: Freecam 1.0.8
		gbfabrictools: GBfabrictools 1.3.4+1.19
		glowingbanners: Glow Banners 1.2.0
		held-item-info: Held Item Info 1.3.0
		illuminations: Illuminations 1.10.5
		indium: Indium 1.0.6+mc1.19
		interdimensional-map-markers: Interdimensional Map Markers 1.0.1
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.5
		jankson: Jankson 4.1.1+j1.2.1
		java: OpenJDK 64-Bit Server VM 17
		keepheadnames: Keep Head Names 1.5.1
		kirin: Kirin UI 1.11.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.2.0
		lambdynlights: LambDynamicLights 2.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		libgui: LibGui 6.0.0-beta.5+1.19-pre1
		libninepatch: LibNinePatch 1.1.0
		lightoverlay: Light Overlay 7.0.0
		lithium: Lithium 0.8.0
		loadmyresources: Load My Resources 1.0.1
		mcwbridges: Macaw's Bridges 2.0.3
		mcwfences: Macaw's Fences and Walls 1.0.5
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwpaths: Macaw's Paths and Pavings 1.0.0
		mcwroofs: Macaw's Roofs 2.1.2
		mcwwindows: Macaw's Windows 2.0.3
		microdurability: microDurability 0.3.5+1.19
		microdurability-core: microDurability Core 0.3.5
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		minecraftcapes: MinecraftCapes Mod 12.0.2
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.6.1-MC1.19
		modmenu: Mod Menu 4.0.0
		morebannerfeatures: More Banner Features 1.1.3
		moreflowerpots: com.eternalhelldevs.moreflowerpots 3.0-SNAPSHOT
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		onsoulfire: On Soul Fire 1.19-1
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		org_joml_joml: joml 1.10.4
		paintingcycle: Painting Cycle 1.0.1
		patternedglass: Patterned Glass 3.0.0+1.19
		phosphor: Phosphor 0.8.1
		picturesign: PictureSign 1.4.1
		presencefootsteps: Presence Footsteps 1.6.0
		pride: Pride Lib 1.1.2+1.19
		puzzle: Puzzle 1.3.3
		puzzle-base: Puzzle Base 1.3.3
		puzzle-gui: Puzzle GUI 1.3.3
		puzzle-models: Puzzle Models 1.3.3
		puzzle-splashscreen: Puzzle Splash Screen 1.3.3
		quilt_base: Quilt Base API 2.0.0-beta.2+1.19
		quilt_biome: Quilt Biome API 2.0.0-beta.2+1.19
		quilt_block_extensions: Quilt Block Extensions API 2.0.0-beta.2+1.19
		quilt_client_command: Quilt Client Command API 2.0.0-beta.2+1.19
		quilt_command: Quilt Command API 2.0.0-beta.2+1.19
		quilt_crash_info: Quilt Crash Info 2.0.0-beta.2+1.19
		quilt_dimension: Quilt Dimension API 2.0.0-beta.2+1.19
		quilt_item_group: Quilt Item Group API 2.0.0-beta.2+1.19
		quilt_item_setting: Quilt Item Setting API 2.0.0-beta.2+1.19
		quilt_lifecycle_events: Quilt Lifecycle Events 2.0.0-beta.2+1.19
		quilt_loader: Quilt Loader 0.17.1-beta.2
		quilt_networking: Quilt Networking 2.0.0-beta.2+1.19
		quilt_recipe: Quilt Recipe API 2.0.0-beta.2+1.19
		quilt_registry: Quilt Registry API 2.0.0-beta.2+1.19
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 2.0.0-beta.2+1.19
		quilt_resource_loader: Quilt Resource Loader 2.0.0-beta.2+1.19
		quilt_screen: Quilt Screen API 2.0.0-beta.2+1.19
		quilt_tags: Quilt Tags API 2.0.0-beta.2+1.19
		quilt_tooltip: Quilt Tooltip API 2.0.0-beta.2+1.19
		quilted_fabric_api: Quilted Fabric API 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_api_base: Quilted Fabric API Base 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_command_api_v2: Quilted Fabric Command API (v2) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_message_api_v1: Quilted Fabric Message API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 2.0.0-alpha.3+0.55.3-1.19
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 2.0.0-alpha.3+0.55.3-1.19
		rainbow-shenanigans: Rainbow Shenanigans 1.0.1
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		roughlyenoughitems: Roughly Enough Items 9.0.491
		satin: Satin 1.8.0
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9+1.19
		sign_editor: Better Signs & Frames 0.8.4
		silence: Silence 1.19-fabric0.53.3-1.0.1
		sit: Sit 1.19-20
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		spruceui: SpruceUI 4.0.0+1.19
		sspb: Sodium Shadowy Path Blocks 3.0.0
		status-effect-bars: Status Effect Bars 1.0.1
		stendhal: Stendhal 1.3.3-1.19
		tooltipfix: ToolTip Fix 1.0.5-1.19
		villager-hats: Villager Hats 1.4.1
		visuality: Visuality 0.5.0
		visualoverhaul: VisualOverhaul 4.1.1
		voicechat: Simple Voice Chat 1.19-2.2.46
		waveycapes: WaveyCapes 1.2.0
		wi_zoom: WI Zoom 1.3-MC1.19
		windchimes: Windchimes 1.2.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['EGOIST23'/389, l='ServerLevel[test 1.17]', x=83.58, y=23.00, z=-89.20]]
	Data Packs: vanilla, loadmyresources.hiddenpack (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
	Launched Version: quilt-loader-0.17.1-beta.2-1.19
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 3
	Suspected Mods: Minecraft (minecraft)
![image](https://user-images.githubusercontent.com/86555131/174564238-8bc3712b-4356-4e52-84c7-6e01f311ceae.png)
despite it is my single player world the crash report file refer to server idk why

and here is the latest log file in minecraft folder
[latest.log](https://github.com/AHilyard/Iceberg/files/8939035/latest.log)

possible culprit code is this: (thanks to [AHilyard](https://github.com/AHilyard) to find the problem)
https://github.com/A5b84/interdimensional-map-markers/blob/28729d962128d0041128d74f1a5c4b853ec40a31/src/main/java/io/github/a5b84/interdimensionalmapmarkers/mixin/MapStateMixin.java#L43
a function that removed in 1.19

**Comment by A5b84** [comment]
Fixed in v1.0.2, thanks for reporting!
