### ISSUE TITLE
request: fix MC-144406

### ISSUE THREAD

**Issue by greener-dot-ca** [A5b84/interdimensional-map-markers#3]
This bug makes it so banners don't appear on the last pixel on the edge of a map .. since your mod already plays with maps and markers on them .. any chance you could implement a fix for this low priority Mojang bug?

[MC-144406](https://bugs.mojang.com/browse/MC-144406)

**Comment by A5b84** [comment]
Sorry but I don't really think that fits the scope of the mod, it's probably better suited for a mod dedicated to fixing vanilla issues

**Comment by greener-dot-ca** [comment]
all good, could I commission you to write a mod that fixes the bug?

**Comment by A5b84** [comment]
I haven't looked at what causes this and if it's feasible to fix it, but I guess that would be possible

I won't have time to look into it in the coming weeks though, if you're fine with a bit of waiting

**Comment by greener-dot-ca** [comment]
been waiting years for Mojang to fix it, I can wait a little longer
